### ISSUE TITLE
file not found: C_, country, _bytens_overallupdated.RData

### ISSUE THREAD

**Issue by joshuaschwab** [kbubar/vaccine_prioritization#1]
Thanks very much for making your code public. I am trying to replicate Figure 1 using main.R, but I am getting an error because this file is not found:
`readRDS(paste0("C_", country, "_bytens_overallupdated.RData"))`

If I use _bytens_overall.RData instead of _bytens_overallupdated.RData, I get R0 that appears to be twice the intended value. 

```source("run_sim.R")
source("helper_functions.R")
country    <- "USA"
C          <- readRDS(paste0("C_", country, "_bytens_overall.RData"))  
u_var      <- c(0.4, 0.38, 0.79, 0.86, 0.8, 0.82, 0.88, 0.74, 0.74)/(39.80957/2)  
R0         <- compute_R0(u_var, C)  
print(R0) #I believe this should be 2.6, but it is 5.2  
```

Thanks in advance and sorry if I am just misunderstanding your code.

**Comment by kbubar** [comment]
Hi Josh, sorry about that. We've been updating the preprint and the code has changed a bit. I just pushed the most recent version and so the problem with the contact matrix should be fixed! Let me know if you have any other problems. And just an FYI, I'm working on making the code run faster so there should be a new (and hopefully final) version posted within a week.

**Comment by joshuaschwab** [comment]
Thank you very much for the fast reply. It's working fine now, thanks!
