### ISSUE TITLE
helper_functions.R

### ISSUE THREAD

**Issue by selinsarac** [kbubar/vaccine_prioritization#3]
Hi,
Where these numbers came from in "helper.functions.R". I couldn't get it.

  R_index <- 83 # col number for R
  Rv_index <- 92 # col number for Rv
  Rx_index <- 101 # col number for Rx
  D_index <- 110

**Comment by kbubar** [comment]
They are the dataframe column indices for the first age group (0-9 year olds) for each compartment (R, Rv, Rx and D). The function then iterates through all the age groups. They don't need to change unless you changed the number of compartments or number of age groups.

**Comment by selinsarac** [comment]
Thanks for helpful quick response. wish healthy days!
